Style/EmptyMethod:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
