default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: shorturl_development

test:
  <<: *default
  database: shorturl_test

production:
  <<: *default
  database: shorturl_db
  username: shorturl_db_user
  password: <%= ENV["SHORTURL_DB_PASSWORD"] %>
